# ============================================================================
#  product-service — Deployment + Service + ConfigMap. Owns product_db.
# ============================================================================
apiVersion: v1
kind: ConfigMap
metadata: { name: product-service-config, namespace: ecommerce }
data:
  SERVER_PORT: "8082"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/product_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce
  labels: { app: product-service }
spec:
  replicas: 2
  selector: { matchLabels: { app: product-service } }
  template:
    metadata:
      labels: { app: product-service }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      securityContext: { runAsNonRoot: true, runAsUser: 1000, fsGroup: 1000 }
      containers:
        - name: product-service
          image: ecommerce/product-service:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8082 }]
          envFrom:
            - configMapRef: { name: app-common-config }
            - configMapRef: { name: product-service-config }
          env:
            - { name: SPRING_DATASOURCE_USERNAME, valueFrom: { secretKeyRef: { name: postgres-credentials, key: POSTGRES_USER } } }
            - { name: SPRING_DATASOURCE_PASSWORD, valueFrom: { secretKeyRef: { name: postgres-credentials, key: POSTGRES_PASSWORD } } }
          volumeMounts:
            - { name: jwt-keys, mountPath: /etc/jwt, readOnly: true }
          startupProbe:
            httpGet: { path: /actuator/health/readiness, port: 8082 }
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8082 }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8082 }
            periodSeconds: 15
          resources:
            requests: { cpu: "200m", memory: "384Mi" }
            limits:   { cpu: "1",    memory: "768Mi" }
      volumes:
        - name: jwt-keys
          secret: { secretName: jwt-keys }
---
apiVersion: v1
kind: Service
metadata: { name: product-service, namespace: ecommerce, labels: { app: product-service } }
spec:
  selector: { app: product-service }
  ports: [{ name: http, port: 8082, targetPort: 8082 }]
