spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://product-service:8082}
