spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notification_db
    username: ${POSTGRES_USER:ecommerce}
    password: ${POSTGRES_PASSWORD:ecommerce}
  kafka:
    bootstrap-servers: kafka:29092
  mail:
    host: ${SMTP_HOST:}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
